---
version: '3.4'

services:
  streamlit-rag-0:
    image: streamlit-rag:latest
    build:
      context: ../
      dockerfile: azure_docker/Dockerfile
    ports:
      - 8000:8000
      - 8500:8500
    env_file:
      - ../azure_docker/.env.docker
    environment:
      - BASE_VERBA_API_URL=http://localhost
      - OPENAI_MODEL=gpt-4
      - VERBA_MODEL_CONTEXT_SIZE=8000
      - VERBA_PORT=8000
      - STREAMLIT_PORT=8500
      - CHUNK_SIZE=400
      - WEAVIATE_URL_VERBA=http://weaviate:8080 #http://10.7.1.4:8080
    command: ["bash", "/Verba/docker-chatbot.sh", "0"]
    links:
      - weaviate
    depends_on:
      weaviate:
        condition: service_healthy
    healthcheck:
      test: curl http://localhost:8000/api/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: wlpocrelay-weaviate:1.22.3.2
    ports:
    - 8080:8080
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8080/v1/.well-known/ready || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'

volumes:
  weaviate_data: